################################################################################
#-------------------------------------------------------------------------------
#             'vaccine_actions' orderly repo master script                                              
#-------------------------------------------------------------------------------
################################################################################

# Purpose: Master script runs the tasks in the pipeline found in 'src'

# Set home directory -> add your own path 
setwd("X:/Dariya/pmi2025")

# Load Hipercow package for when using cluster 
library(hipercow)

#-------------------------------------------------------------------------------
#                   SET UP KEY ORDERLY TASK PARAMETERS
#-------------------------------------------------------------------------------

# state if short run TRUE/FALSE
# = TRUE used in development
# = FALSE used for final runs
short_run <- TRUE

# summary of features of short vs long runs
# <TBC FILL OUT LATER> *NTS

#-------------------------------------------------------------------------------
#                          RUN ORDERLY TASKS
#-------------------------------------------------------------------------------
# <Note: this pipeline may branch so should make it explicit which tasks linked
# to which> *NTS

#===============================================================================
#-------------------------------------------------------------------------------
# Task name    : 'read_in'
# Purpose      : to read in any data that is not generated by this workflow but
#                is utilised within one or many of the task stages
#                (keeps all outside data in one place!)   
# Order        : First task
# Run time     : Very short, less than a second
# Run location : Locally
#-------------------------------------------------------------------------------
# Run
orderly::orderly_run(
  name = "read_in",  
  echo = FALSE      #toggle TRUE/FALSE to print log
)

#===============================================================================
#-------------------------------------------------------------------------------
# Task name    : 'find_pop_equilibrium'
# Purpose      : to run the population-level XPVWRH gonovax model to equilibrium
#                given the parameters provided
# Order        : read_in -> find_pop_equilibrium
# Run time     : Long run & 3 erlang ~ 2min, short run & 1 erlang = 1 second
# Run location : Locally
#-------------------------------------------------------------------------------

# Set parameters:
n_erlang  <- 3       #3 for most model runs, 1 for explaining each VAx plots
short_run <- TRUE  #TRUE for development (10 parameter sets), FALSE otherwise
                      #(1e03 parameter sets)

# Run:
orderly::orderly_run(
  name = "find_pop_equilibrium",  
  parameters = list(n_erlang = n_erlang,
                    short_run = short_run),
  echo = TRUE      #toggle TRUE/FALSE to print log
)

#===============================================================================
#-------------------------------------------------------------------------------
# Task name    : 'gen_trial_parameters'
# Purpose      : i) to modify the NG popualtion-level parameters to fit a 
#               high-risk trial cohort, ii) generate vaccine profiles of VAa, 
#               VAs, and VAd.
# Order        : find_pop_equilibrium -> gen_trial_parameters
# Run time     : <TBC ADD> *NTS
# Run location : <TBC ADD> *NTS
#-------------------------------------------------------------------------------


