################################################################################

#                         orderly task: 'read_in' 

################################################################################ 

# THIS ORDERLY TASK'S OBJECTIVE IS TO:------------------------------------------
# - Read in any data that is not generated by this workflow that is utilised
#   in any part of this workflow in order to (i) organise all inputs into one
#   location, (ii) facilitate tracking of what version of the data is being
#   used downstream, (iii) pre-process input files as necessary

# N.B Any new data to be used should be pasted into the 'data' folder, then 
# 'artefacts' updated, and the task to be re-run

#-------------------------------------------------------------------------------        
# Set up
#-------------------------------------------------------------------------------
# Generate output folders  
dir.create("outputs", showWarnings = FALSE)

# State input folder is a resource
orderly_resource("data")

#-------------------------------------------------------------------------------        
# Artefacts
#-------------------------------------------------------------------------------
orderly::orderly_artefact(
  description = 
    " rds saves of the gonorrhoea and health economic parameters",
  files = "outputs/gp_params.rds"
)

#-------------------------------------------------------------------------------        
# Load Resources
#-------------------------------------------------------------------------------
parameters <- readRDS("data/parameters.rds")

#-------------------------------------------------------------------------------        
# Process
#-------------------------------------------------------------------------------

## 1. Remove superfluous elements from ng parameters
#  menzb efficacy not used downstream
#  (N.B have kept 1st and 2nd dose uptake just incase)
parameters$vaccine <- parameters$vaccine[names(parameters$vaccine)
                                         != "menzb_efficacy"]
# 2. Add in filler-parameters (updates to package that do not affect our
#  analysis)
for(i in seq_along(parameters$gono)){
  parameters$gono[[i]]$kappa <- 0
  parameters$gono[[i]]$notifiedprev <- 0
}

#-------------------------------------------------------------------------------        
# Save
#-------------------------------------------------------------------------------
saveRDS(parameters, "outputs/gp_params.rds")
